using System;
using System.Collections.Generic;
using Google.Protobuf;

namespace DH.Proto
{
	public static class MsgType
	{
		public static readonly Dictionary<ReqGameMsg, Func<IMessage>> ReqGameMsgDict = new Dictionary<ReqGameMsg, Func<IMessage>>
		{
			{ReqGameMsg.ReqSync, ()=>new ReqSync()},
			{ReqGameMsg.ReqFbReport, ()=>new ReqFbReport()},
			{ReqGameMsg.ReqNotifyMsg, ()=>new ReqNotifyMsg()},
			{ReqGameMsg.ReqNotify, ()=>new ReqNotify()},
			{ReqGameMsg.ReqAdUpload, ()=>new ReqAdUpload()},
			{ReqGameMsg.ReqGm, ()=>new ReqGm()},
			{ReqGameMsg.ReqGmSync, ()=>new ReqGmSync()},
			{ReqGameMsg.ReqBattleGm, ()=>new ReqBattleGm()},
			{ReqGameMsg.ReqPrePay, ()=>new ReqPrePay()},
			{ReqGameMsg.ReqRewardPay, ()=>new ReqRewardPay()},
			{ReqGameMsg.ReqLoginRewardPay, ()=>new ReqLoginRewardPay()},
			{ReqGameMsg.ReqLivesGet, ()=>new ReqLivesGet()},
			{ReqGameMsg.ReqLivesSync, ()=>new ReqLivesSync()},
			{ReqGameMsg.ReqMailRead, ()=>new ReqMailRead()},
			{ReqGameMsg.ReqMailReward, ()=>new ReqMailReward()},
			{ReqGameMsg.ReqMailDelete, ()=>new ReqMailDelete()},
			{ReqGameMsg.ReqMailSync, ()=>new ReqMailSync()},
			{ReqGameMsg.ReqEquipWearOp, ()=>new ReqEquipWearOp()},
			{ReqGameMsg.ReqEquipLevelUp, ()=>new ReqEquipLevelUp()},
			{ReqGameMsg.ReqEquipSwitch, ()=>new ReqEquipSwitch()},
			{ReqGameMsg.ReqMainFightBegin, ()=>new ReqMainFightBegin()},
			{ReqGameMsg.ReqMainFightEnd, ()=>new ReqMainFightEnd()},
			{ReqGameMsg.ReqMainFightAdDouble, ()=>new ReqMainFightAdDouble()},
			{ReqGameMsg.ReqMainFightBox, ()=>new ReqMainFightBox()},
			{ReqGameMsg.ReqMainFightArchiveBegin, ()=>new ReqMainFightArchiveBegin()},
			{ReqGameMsg.ReqMainHangupClaim, ()=>new ReqMainHangupClaim()},
			{ReqGameMsg.ReqBattleEquipRefresh, ()=>new ReqBattleEquipRefresh()},
			{ReqGameMsg.ReqBattleTalentRefresh, ()=>new ReqBattleTalentRefresh()},
			{ReqGameMsg.ReqBattleTalentSelect, ()=>new ReqBattleTalentSelect()},
			{ReqGameMsg.ReqBattleLvUp, ()=>new ReqBattleLvUp()},
			{ReqGameMsg.ReqBattleWaveDone, ()=>new ReqBattleWaveDone()},
			{ReqGameMsg.ReqBattleEquipSkillSelect, ()=>new ReqBattleEquipSkillSelect()},
			{ReqGameMsg.ReqBattleEndlessEquip, ()=>new ReqBattleEndlessEquip()},
			{ReqGameMsg.ReqBattleEndlessWaveDone, ()=>new ReqBattleEndlessWaveDone()},
			{ReqGameMsg.ReqFightRevive, ()=>new ReqFightRevive()},
			{ReqGameMsg.ReqChangeName, ()=>new ReqChangeName()},
			{ReqGameMsg.ReqRankOp, ()=>new ReqRankOp()},
			{ReqGameMsg.ReqRankDigest, ()=>new ReqRankDigest()},
			{ReqGameMsg.ReqHeadOp, ()=>new ReqHeadOp()},
			{ReqGameMsg.ReqRedeemExchange, ()=>new ReqRedeemExchange()},
			{ReqGameMsg.ReqDiscordSync, ()=>new ReqDiscordSync()},
			{ReqGameMsg.ReqItemUseFreeAd, ()=>new ReqItemUseFreeAd()},
			{ReqGameMsg.ReqInviteReport, ()=>new ReqInviteReport()},
			{ReqGameMsg.ReqInviteSync, ()=>new ReqInviteSync()},
			{ReqGameMsg.ReqInviteClaim, ()=>new ReqInviteClaim()},
			{ReqGameMsg.ReqMonthCardClaim, ()=>new ReqMonthCardClaim()},
			{ReqGameMsg.ReqMonthCardDoubleClaim, ()=>new ReqMonthCardDoubleClaim()},
			{ReqGameMsg.ReqShopDailyBuy, ()=>new ReqShopDailyBuy()},
			{ReqGameMsg.ReqShopRecruitBuy, ()=>new ReqShopRecruitBuy()},
			{ReqGameMsg.ReqShopPackageBuy, ()=>new ReqShopPackageBuy()},
			{ReqGameMsg.ReqShopRecruitEquip, ()=>new ReqShopRecruitEquip()},
			{ReqGameMsg.ReqFirstChargeClaim, ()=>new ReqFirstChargeClaim()},
			{ReqGameMsg.ReqHeroUnlock, ()=>new ReqHeroUnlock()},
			{ReqGameMsg.ReqHeroLvUp, ()=>new ReqHeroLvUp()},
			{ReqGameMsg.ReqHeroStarUp, ()=>new ReqHeroStarUp()},
			{ReqGameMsg.ReqHeroInBattle, ()=>new ReqHeroInBattle()},
			{ReqGameMsg.ReqHeroReset, ()=>new ReqHeroReset()},
			{ReqGameMsg.ReqHeroLvUpAuto, ()=>new ReqHeroLvUpAuto()},
			{ReqGameMsg.ReqEndlessBegin, ()=>new ReqEndlessBegin()},
			{ReqGameMsg.ReqEndlessEnd, ()=>new ReqEndlessEnd()},
			{ReqGameMsg.ReqEndlessArchiveBegin, ()=>new ReqEndlessArchiveBegin()},
			{ReqGameMsg.ReqEndlessSweep, ()=>new ReqEndlessSweep()},
			{ReqGameMsg.ReqPassportClaim, ()=>new ReqPassportClaim()},
			{ReqGameMsg.ReqPassportUnlock, ()=>new ReqPassportUnlock()},
			{ReqGameMsg.ReqDailyPackClaim, ()=>new ReqDailyPackClaim()},
			{ReqGameMsg.ReqDailyPackSelect, ()=>new ReqDailyPackSelect()},
			{ReqGameMsg.ReqDailyPackOptional, ()=>new ReqDailyPackOptional()},
			{ReqGameMsg.ReqLuckyDraw, ()=>new ReqLuckyDraw()},
			{ReqGameMsg.ReqLuckyClaim, ()=>new ReqLuckyClaim()},
			{ReqGameMsg.ReqTriggerGiftConditionBuy, ()=>new ReqTriggerGiftConditionBuy()},
			{ReqGameMsg.ReqTriggerGiftClaim, ()=>new ReqTriggerGiftClaim()},
			{ReqGameMsg.ReqDailyFightBegin, ()=>new ReqDailyFightBegin()},
			{ReqGameMsg.ReqDailyFightEnd, ()=>new ReqDailyFightEnd()},
			{ReqGameMsg.ReqDailyFightArchiveBegin, ()=>new ReqDailyFightArchiveBegin()},
			{ReqGameMsg.ReqDailyFightBox, ()=>new ReqDailyFightBox()},
			{ReqGameMsg.ReqDailyFightWeekBox, ()=>new ReqDailyFightWeekBox()},
			{ReqGameMsg.ReqDailyFightSweep, ()=>new ReqDailyFightSweep()},
			{ReqGameMsg.ReqMagicDraw, ()=>new ReqMagicDraw()},
			{ReqGameMsg.ReqMagicClaim, ()=>new ReqMagicClaim()},
			{ReqGameMsg.ReqMagicFundClaim, ()=>new ReqMagicFundClaim()},
			{ReqGameMsg.ReqSecretFightBegin, ()=>new ReqSecretFightBegin()},
			{ReqGameMsg.ReqSecretFightEnd, ()=>new ReqSecretFightEnd()},
			{ReqGameMsg.ReqSecretFightBox, ()=>new ReqSecretFightBox()},
			{ReqGameMsg.ReqSecretFightArchiveBegin, ()=>new ReqSecretFightArchiveBegin()},
			{ReqGameMsg.ReqSecretBattleTalentRefresh, ()=>new ReqSecretBattleTalentRefresh()},
			{ReqGameMsg.ReqSecretBattleTalentSelect, ()=>new ReqSecretBattleTalentSelect()},
			{ReqGameMsg.ReqSecretBattleWaveDone, ()=>new ReqSecretBattleWaveDone()},
			{ReqGameMsg.ReqSecretBattleEquipSkillSelect, ()=>new ReqSecretBattleEquipSkillSelect()},
			{ReqGameMsg.ReqHeroEquipWear, ()=>new ReqHeroEquipWear()},
			{ReqGameMsg.ReqHeroEquipLevelUp, ()=>new ReqHeroEquipLevelUp()},
			{ReqGameMsg.ReqHeroEquipDown, ()=>new ReqHeroEquipDown()},
			{ReqGameMsg.ReqHeroEquipMerge, ()=>new ReqHeroEquipMerge()},
			{ReqGameMsg.ReqHeroEquipMergeFast, ()=>new ReqHeroEquipMergeFast()},
			{ReqGameMsg.ReqSchoolTaskClaim, ()=>new ReqSchoolTaskClaim()},
			{ReqGameMsg.ReqSchoolScoreClaim, ()=>new ReqSchoolScoreClaim()},
			{ReqGameMsg.ReqSchoolFundClaim, ()=>new ReqSchoolFundClaim()},
			{ReqGameMsg.ReqLuckyTrip, ()=>new ReqLuckyTrip()},
			{ReqGameMsg.ReqLuckyTripClaim, ()=>new ReqLuckyTripClaim()},
			{ReqGameMsg.ReqLuckyTripPullRecord, ()=>new ReqLuckyTripPullRecord()},
			{ReqGameMsg.ReqMagicAgeClaim, ()=>new ReqMagicAgeClaim()},
			{ReqGameMsg.ReqGiftPackZeroClaim, ()=>new ReqGiftPackZeroClaim()},
			{ReqGameMsg.ReqLuckyEggBuy, ()=>new ReqLuckyEggBuy()},
			{ReqGameMsg.ReqLuckyEggClaim, ()=>new ReqLuckyEggClaim()},
			{ReqGameMsg.ReqLuckyEggTaskClaim, ()=>new ReqLuckyEggTaskClaim()},
			{ReqGameMsg.ReqLuckyEggFundClaim, ()=>new ReqLuckyEggFundClaim()},
			{ReqGameMsg.ReqLuckyEggExchange, ()=>new ReqLuckyEggExchange()},
			{ReqGameMsg.ReqLuckyEggDraw, ()=>new ReqLuckyEggDraw()},
			{ReqGameMsg.ReqBingoCoinBuy, ()=>new ReqBingoCoinBuy()},
			{ReqGameMsg.ReqBingoOpen, ()=>new ReqBingoOpen()},
			{ReqGameMsg.ReqBingoClaim, ()=>new ReqBingoClaim()},
			{ReqGameMsg.ReqBingoReset, ()=>new ReqBingoReset()},
			{ReqGameMsg.ReqBingoTaskClaim, ()=>new ReqBingoTaskClaim()},
			{ReqGameMsg.ReqBingoExchange, ()=>new ReqBingoExchange()},
			{ReqGameMsg.ReqAccountAuth, ()=>new ReqAccountAuth()},
			{ReqGameMsg.ReqCreateRole, ()=>new ReqCreateRole()},
			{ReqGameMsg.ReqLoginRole, ()=>new ReqLoginRole()},
			{ReqGameMsg.ReqServersAndRoles, ()=>new ReqServersAndRoles()},
			{ReqGameMsg.ReqUnRegisterAccountStatus, ()=>new ReqUnRegisterAccountStatus()},
			{ReqGameMsg.ReqUnRegisterAccount, ()=>new ReqUnRegisterAccount()},
			{ReqGameMsg.ReqCancelUnRegisterAccount, ()=>new ReqCancelUnRegisterAccount()},
			{ReqGameMsg.ReqRoleFastLogin, ()=>new ReqRoleFastLogin()},
			{ReqGameMsg.ReqQuicklyLoginRole, ()=>new ReqQuicklyLoginRole()},
			{ReqGameMsg.ReqVsn, ()=>new ReqVsn()},
			{ReqGameMsg.ReqNotice, ()=>new ReqNotice()},
		};

		public static readonly Dictionary<RspGameMsg, Func<IMessage>> RspGameMsgDict = new Dictionary<RspGameMsg, Func<IMessage>>
		{
			{RspGameMsg.RspSync, ()=>new RspSync()},
			{RspGameMsg.RspFbReport, ()=>new RspFbReport()},
			{RspGameMsg.RspNotifyMsg, ()=>new RspNotifyMsg()},
			{RspGameMsg.RspNotify, ()=>new RspNotify()},
			{RspGameMsg.RspAdUpload, ()=>new RspAdUpload()},
			{RspGameMsg.RspGm, ()=>new RspGm()},
			{RspGameMsg.RspGmSync, ()=>new RspGmSync()},
			{RspGameMsg.RspBattleGm, ()=>new RspBattleGm()},
			{RspGameMsg.RspPrePay, ()=>new RspPrePay()},
			{RspGameMsg.RspRewardPay, ()=>new RspRewardPay()},
			{RspGameMsg.RspLoginRewardPay, ()=>new RspLoginRewardPay()},
			{RspGameMsg.RspLivesGet, ()=>new RspLivesGet()},
			{RspGameMsg.RspLivesSync, ()=>new RspLivesSync()},
			{RspGameMsg.RspMailRead, ()=>new RspMailRead()},
			{RspGameMsg.RspMailReward, ()=>new RspMailReward()},
			{RspGameMsg.RspMailDelete, ()=>new RspMailDelete()},
			{RspGameMsg.RspMailSync, ()=>new RspMailSync()},
			{RspGameMsg.RspEquipWearOp, ()=>new RspEquipWearOp()},
			{RspGameMsg.RspEquipLevelUp, ()=>new RspEquipLevelUp()},
			{RspGameMsg.RspEquipSwitch, ()=>new RspEquipSwitch()},
			{RspGameMsg.RspMainFightBegin, ()=>new RspMainFightBegin()},
			{RspGameMsg.RspMainFightEnd, ()=>new RspMainFightEnd()},
			{RspGameMsg.RspMainFightAdDouble, ()=>new RspMainFightAdDouble()},
			{RspGameMsg.RspMainFightBox, ()=>new RspMainFightBox()},
			{RspGameMsg.RspMainFightArchiveBegin, ()=>new RspMainFightArchiveBegin()},
			{RspGameMsg.RspMainHangupClaim, ()=>new RspMainHangupClaim()},
			{RspGameMsg.RspBattleEquipRefresh, ()=>new RspBattleEquipRefresh()},
			{RspGameMsg.RspBattleTalentRefresh, ()=>new RspBattleTalentRefresh()},
			{RspGameMsg.RspBattleTalentSelect, ()=>new RspBattleTalentSelect()},
			{RspGameMsg.RspBattleLvUp, ()=>new RspBattleLvUp()},
			{RspGameMsg.RspBattleWaveDone, ()=>new RspBattleWaveDone()},
			{RspGameMsg.RspBattleEquipSkillSelect, ()=>new RspBattleEquipSkillSelect()},
			{RspGameMsg.RspBattleEndlessEquip, ()=>new RspBattleEndlessEquip()},
			{RspGameMsg.RspBattleEndlessWaveDone, ()=>new RspBattleEndlessWaveDone()},
			{RspGameMsg.RspFightRevive, ()=>new RspFightRevive()},
			{RspGameMsg.RspChangeName, ()=>new RspChangeName()},
			{RspGameMsg.RspRankOp, ()=>new RspRankOp()},
			{RspGameMsg.RspRankDigest, ()=>new RspRankDigest()},
			{RspGameMsg.RspHeadOp, ()=>new RspHeadOp()},
			{RspGameMsg.RspRedeemExchange, ()=>new RspRedeemExchange()},
			{RspGameMsg.RspDiscordSync, ()=>new RspDiscordSync()},
			{RspGameMsg.RspItemUseFreeAd, ()=>new RspItemUseFreeAd()},
			{RspGameMsg.RspInviteReport, ()=>new RspInviteReport()},
			{RspGameMsg.RspInviteSync, ()=>new RspInviteSync()},
			{RspGameMsg.RspInviteClaim, ()=>new RspInviteClaim()},
			{RspGameMsg.RspMonthCardClaim, ()=>new RspMonthCardClaim()},
			{RspGameMsg.RspMonthCardDoubleClaim, ()=>new RspMonthCardDoubleClaim()},
			{RspGameMsg.RspShopDailyBuy, ()=>new RspShopDailyBuy()},
			{RspGameMsg.RspShopRecruitBuy, ()=>new RspShopRecruitBuy()},
			{RspGameMsg.RspShopPackageBuy, ()=>new RspShopPackageBuy()},
			{RspGameMsg.RspShopRecruitEquip, ()=>new RspShopRecruitEquip()},
			{RspGameMsg.RspFirstChargeClaim, ()=>new RspFirstChargeClaim()},
			{RspGameMsg.RspHeroUnlock, ()=>new RspHeroUnlock()},
			{RspGameMsg.RspHeroLvUp, ()=>new RspHeroLvUp()},
			{RspGameMsg.RspHeroStarUp, ()=>new RspHeroStarUp()},
			{RspGameMsg.RspHeroInBattle, ()=>new RspHeroInBattle()},
			{RspGameMsg.RspHeroReset, ()=>new RspHeroReset()},
			{RspGameMsg.RspHeroLvUpAuto, ()=>new RspHeroLvUpAuto()},
			{RspGameMsg.RspEndlessBegin, ()=>new RspEndlessBegin()},
			{RspGameMsg.RspEndlessEnd, ()=>new RspEndlessEnd()},
			{RspGameMsg.RspEndlessArchiveBegin, ()=>new RspEndlessArchiveBegin()},
			{RspGameMsg.RspEndlessSweep, ()=>new RspEndlessSweep()},
			{RspGameMsg.RspPassportClaim, ()=>new RspPassportClaim()},
			{RspGameMsg.RspPassportUnlock, ()=>new RspPassportUnlock()},
			{RspGameMsg.RspDailyPackClaim, ()=>new RspDailyPackClaim()},
			{RspGameMsg.RspDailyPackSelect, ()=>new RspDailyPackSelect()},
			{RspGameMsg.RspDailyPackOptional, ()=>new RspDailyPackOptional()},
			{RspGameMsg.RspLuckyDraw, ()=>new RspLuckyDraw()},
			{RspGameMsg.RspLuckyClaim, ()=>new RspLuckyClaim()},
			{RspGameMsg.RspTriggerGiftConditionBuy, ()=>new RspTriggerGiftConditionBuy()},
			{RspGameMsg.RspTriggerGiftClaim, ()=>new RspTriggerGiftClaim()},
			{RspGameMsg.RspDailyFightBegin, ()=>new RspDailyFightBegin()},
			{RspGameMsg.RspDailyFightEnd, ()=>new RspDailyFightEnd()},
			{RspGameMsg.RspDailyFightArchiveBegin, ()=>new RspDailyFightArchiveBegin()},
			{RspGameMsg.RspDailyFightBox, ()=>new RspDailyFightBox()},
			{RspGameMsg.RspDailyFightWeekBox, ()=>new RspDailyFightWeekBox()},
			{RspGameMsg.RspDailyFightSweep, ()=>new RspDailyFightSweep()},
			{RspGameMsg.RspMagicDraw, ()=>new RspMagicDraw()},
			{RspGameMsg.RspMagicClaim, ()=>new RspMagicClaim()},
			{RspGameMsg.RspMagicFundClaim, ()=>new RspMagicFundClaim()},
			{RspGameMsg.RspSecretFightBegin, ()=>new RspSecretFightBegin()},
			{RspGameMsg.RspSecretFightEnd, ()=>new RspSecretFightEnd()},
			{RspGameMsg.RspSecretFightBox, ()=>new RspSecretFightBox()},
			{RspGameMsg.RspSecretFightArchiveBegin, ()=>new RspSecretFightArchiveBegin()},
			{RspGameMsg.RspSecretBattleTalentRefresh, ()=>new RspSecretBattleTalentRefresh()},
			{RspGameMsg.RspSecretBattleTalentSelect, ()=>new RspSecretBattleTalentSelect()},
			{RspGameMsg.RspSecretBattleWaveDone, ()=>new RspSecretBattleWaveDone()},
			{RspGameMsg.RspSecretBattleEquipSkillSelect, ()=>new RspSecretBattleEquipSkillSelect()},
			{RspGameMsg.RspHeroEquipWear, ()=>new RspHeroEquipWear()},
			{RspGameMsg.RspHeroEquipLevelUp, ()=>new RspHeroEquipLevelUp()},
			{RspGameMsg.RspHeroEquipDown, ()=>new RspHeroEquipDown()},
			{RspGameMsg.RspHeroEquipMerge, ()=>new RspHeroEquipMerge()},
			{RspGameMsg.RspHeroEquipMergeFast, ()=>new RspHeroEquipMergeFast()},
			{RspGameMsg.RspSchoolTaskClaim, ()=>new RspSchoolTaskClaim()},
			{RspGameMsg.RspSchoolScoreClaim, ()=>new RspSchoolScoreClaim()},
			{RspGameMsg.RspSchoolFundClaim, ()=>new RspSchoolFundClaim()},
			{RspGameMsg.RspLuckyTrip, ()=>new RspLuckyTrip()},
			{RspGameMsg.RspLuckyTripClaim, ()=>new RspLuckyTripClaim()},
			{RspGameMsg.RspLuckyTripPullRecord, ()=>new RspLuckyTripPullRecord()},
			{RspGameMsg.RspMagicAgeClaim, ()=>new RspMagicAgeClaim()},
			{RspGameMsg.RspGiftPackZeroClaim, ()=>new RspGiftPackZeroClaim()},
			{RspGameMsg.RspLuckyEggBuy, ()=>new RspLuckyEggBuy()},
			{RspGameMsg.RspLuckyEggClaim, ()=>new RspLuckyEggClaim()},
			{RspGameMsg.RspLuckyEggTaskClaim, ()=>new RspLuckyEggTaskClaim()},
			{RspGameMsg.RspLuckyEggFundClaim, ()=>new RspLuckyEggFundClaim()},
			{RspGameMsg.RspLuckyEggExchange, ()=>new RspLuckyEggExchange()},
			{RspGameMsg.RspLuckyEggDraw, ()=>new RspLuckyEggDraw()},
			{RspGameMsg.RspBingoCoinBuy, ()=>new RspBingoCoinBuy()},
			{RspGameMsg.RspBingoOpen, ()=>new RspBingoOpen()},
			{RspGameMsg.RspBingoClaim, ()=>new RspBingoClaim()},
			{RspGameMsg.RspBingoReset, ()=>new RspBingoReset()},
			{RspGameMsg.RspBingoTaskClaim, ()=>new RspBingoTaskClaim()},
			{RspGameMsg.RspBingoExchange, ()=>new RspBingoExchange()},
			{RspGameMsg.RspAccountAuth, ()=>new RspAccountAuth()},
			{RspGameMsg.RspCreateRole, ()=>new RspCreateRole()},
			{RspGameMsg.RspLoginRole, ()=>new RspLoginRole()},
			{RspGameMsg.RspServersAndRoles, ()=>new RspServersAndRoles()},
			{RspGameMsg.RspAntiKick, ()=>new RspAntiKick()},
			{RspGameMsg.RspUnRegisterAccountStatus, ()=>new RspUnRegisterAccountStatus()},
			{RspGameMsg.RspUnRegisterAccount, ()=>new RspUnRegisterAccount()},
			{RspGameMsg.RspCancelUnRegisterAccount, ()=>new RspCancelUnRegisterAccount()},
			{RspGameMsg.RspRoleFastLogin, ()=>new RspRoleFastLogin()},
			{RspGameMsg.RspQuicklyLoginRole, ()=>new RspQuicklyLoginRole()},
			{RspGameMsg.RspVsn, ()=>new RspVsn()},
			{RspGameMsg.RspNotice, ()=>new RspNotice()},
			{RspGameMsg.RspPushNotice, ()=>new RspPushNotice()},
			{RspGameMsg.RspNewMail, ()=>new RspNewMail()},
			{RspGameMsg.RspNewSysMail, ()=>new RspNewSysMail()},
			{RspGameMsg.RspAnnouncement, ()=>new RspAnnouncement()},
		};
		public static readonly Dictionary<Type, RspGameMsg> RspType = new Dictionary<Type, RspGameMsg>
		{
			{typeof(RspSync), RspGameMsg.RspSync},
			{typeof(RspFbReport), RspGameMsg.RspFbReport},
			{typeof(RspNotifyMsg), RspGameMsg.RspNotifyMsg},
			{typeof(RspNotify), RspGameMsg.RspNotify},
			{typeof(RspAdUpload), RspGameMsg.RspAdUpload},
			{typeof(RspGm), RspGameMsg.RspGm},
			{typeof(RspGmSync), RspGameMsg.RspGmSync},
			{typeof(RspBattleGm), RspGameMsg.RspBattleGm},
			{typeof(RspPrePay), RspGameMsg.RspPrePay},
			{typeof(RspRewardPay), RspGameMsg.RspRewardPay},
			{typeof(RspLoginRewardPay), RspGameMsg.RspLoginRewardPay},
			{typeof(RspLivesGet), RspGameMsg.RspLivesGet},
			{typeof(RspLivesSync), RspGameMsg.RspLivesSync},
			{typeof(RspMailRead), RspGameMsg.RspMailRead},
			{typeof(RspMailReward), RspGameMsg.RspMailReward},
			{typeof(RspMailDelete), RspGameMsg.RspMailDelete},
			{typeof(RspMailSync), RspGameMsg.RspMailSync},
			{typeof(RspEquipWearOp), RspGameMsg.RspEquipWearOp},
			{typeof(RspEquipLevelUp), RspGameMsg.RspEquipLevelUp},
			{typeof(RspEquipSwitch), RspGameMsg.RspEquipSwitch},
			{typeof(RspMainFightBegin), RspGameMsg.RspMainFightBegin},
			{typeof(RspMainFightEnd), RspGameMsg.RspMainFightEnd},
			{typeof(RspMainFightAdDouble), RspGameMsg.RspMainFightAdDouble},
			{typeof(RspMainFightBox), RspGameMsg.RspMainFightBox},
			{typeof(RspMainFightArchiveBegin), RspGameMsg.RspMainFightArchiveBegin},
			{typeof(RspMainHangupClaim), RspGameMsg.RspMainHangupClaim},
			{typeof(RspBattleEquipRefresh), RspGameMsg.RspBattleEquipRefresh},
			{typeof(RspBattleTalentRefresh), RspGameMsg.RspBattleTalentRefresh},
			{typeof(RspBattleTalentSelect), RspGameMsg.RspBattleTalentSelect},
			{typeof(RspBattleLvUp), RspGameMsg.RspBattleLvUp},
			{typeof(RspBattleWaveDone), RspGameMsg.RspBattleWaveDone},
			{typeof(RspBattleEquipSkillSelect), RspGameMsg.RspBattleEquipSkillSelect},
			{typeof(RspBattleEndlessEquip), RspGameMsg.RspBattleEndlessEquip},
			{typeof(RspBattleEndlessWaveDone), RspGameMsg.RspBattleEndlessWaveDone},
			{typeof(RspFightRevive), RspGameMsg.RspFightRevive},
			{typeof(RspChangeName), RspGameMsg.RspChangeName},
			{typeof(RspRankOp), RspGameMsg.RspRankOp},
			{typeof(RspRankDigest), RspGameMsg.RspRankDigest},
			{typeof(RspHeadOp), RspGameMsg.RspHeadOp},
			{typeof(RspRedeemExchange), RspGameMsg.RspRedeemExchange},
			{typeof(RspDiscordSync), RspGameMsg.RspDiscordSync},
			{typeof(RspItemUseFreeAd), RspGameMsg.RspItemUseFreeAd},
			{typeof(RspInviteReport), RspGameMsg.RspInviteReport},
			{typeof(RspInviteSync), RspGameMsg.RspInviteSync},
			{typeof(RspInviteClaim), RspGameMsg.RspInviteClaim},
			{typeof(RspMonthCardClaim), RspGameMsg.RspMonthCardClaim},
			{typeof(RspMonthCardDoubleClaim), RspGameMsg.RspMonthCardDoubleClaim},
			{typeof(RspShopDailyBuy), RspGameMsg.RspShopDailyBuy},
			{typeof(RspShopRecruitBuy), RspGameMsg.RspShopRecruitBuy},
			{typeof(RspShopPackageBuy), RspGameMsg.RspShopPackageBuy},
			{typeof(RspShopRecruitEquip), RspGameMsg.RspShopRecruitEquip},
			{typeof(RspFirstChargeClaim), RspGameMsg.RspFirstChargeClaim},
			{typeof(RspHeroUnlock), RspGameMsg.RspHeroUnlock},
			{typeof(RspHeroLvUp), RspGameMsg.RspHeroLvUp},
			{typeof(RspHeroStarUp), RspGameMsg.RspHeroStarUp},
			{typeof(RspHeroInBattle), RspGameMsg.RspHeroInBattle},
			{typeof(RspHeroReset), RspGameMsg.RspHeroReset},
			{typeof(RspHeroLvUpAuto), RspGameMsg.RspHeroLvUpAuto},
			{typeof(RspEndlessBegin), RspGameMsg.RspEndlessBegin},
			{typeof(RspEndlessEnd), RspGameMsg.RspEndlessEnd},
			{typeof(RspEndlessArchiveBegin), RspGameMsg.RspEndlessArchiveBegin},
			{typeof(RspEndlessSweep), RspGameMsg.RspEndlessSweep},
			{typeof(RspPassportClaim), RspGameMsg.RspPassportClaim},
			{typeof(RspPassportUnlock), RspGameMsg.RspPassportUnlock},
			{typeof(RspDailyPackClaim), RspGameMsg.RspDailyPackClaim},
			{typeof(RspDailyPackSelect), RspGameMsg.RspDailyPackSelect},
			{typeof(RspDailyPackOptional), RspGameMsg.RspDailyPackOptional},
			{typeof(RspLuckyDraw), RspGameMsg.RspLuckyDraw},
			{typeof(RspLuckyClaim), RspGameMsg.RspLuckyClaim},
			{typeof(RspTriggerGiftConditionBuy), RspGameMsg.RspTriggerGiftConditionBuy},
			{typeof(RspTriggerGiftClaim), RspGameMsg.RspTriggerGiftClaim},
			{typeof(RspDailyFightBegin), RspGameMsg.RspDailyFightBegin},
			{typeof(RspDailyFightEnd), RspGameMsg.RspDailyFightEnd},
			{typeof(RspDailyFightArchiveBegin), RspGameMsg.RspDailyFightArchiveBegin},
			{typeof(RspDailyFightBox), RspGameMsg.RspDailyFightBox},
			{typeof(RspDailyFightWeekBox), RspGameMsg.RspDailyFightWeekBox},
			{typeof(RspDailyFightSweep), RspGameMsg.RspDailyFightSweep},
			{typeof(RspMagicDraw), RspGameMsg.RspMagicDraw},
			{typeof(RspMagicClaim), RspGameMsg.RspMagicClaim},
			{typeof(RspMagicFundClaim), RspGameMsg.RspMagicFundClaim},
			{typeof(RspSecretFightBegin), RspGameMsg.RspSecretFightBegin},
			{typeof(RspSecretFightEnd), RspGameMsg.RspSecretFightEnd},
			{typeof(RspSecretFightBox), RspGameMsg.RspSecretFightBox},
			{typeof(RspSecretFightArchiveBegin), RspGameMsg.RspSecretFightArchiveBegin},
			{typeof(RspSecretBattleTalentRefresh), RspGameMsg.RspSecretBattleTalentRefresh},
			{typeof(RspSecretBattleTalentSelect), RspGameMsg.RspSecretBattleTalentSelect},
			{typeof(RspSecretBattleWaveDone), RspGameMsg.RspSecretBattleWaveDone},
			{typeof(RspSecretBattleEquipSkillSelect), RspGameMsg.RspSecretBattleEquipSkillSelect},
			{typeof(RspHeroEquipWear), RspGameMsg.RspHeroEquipWear},
			{typeof(RspHeroEquipLevelUp), RspGameMsg.RspHeroEquipLevelUp},
			{typeof(RspHeroEquipDown), RspGameMsg.RspHeroEquipDown},
			{typeof(RspHeroEquipMerge), RspGameMsg.RspHeroEquipMerge},
			{typeof(RspHeroEquipMergeFast), RspGameMsg.RspHeroEquipMergeFast},
			{typeof(RspSchoolTaskClaim), RspGameMsg.RspSchoolTaskClaim},
			{typeof(RspSchoolScoreClaim), RspGameMsg.RspSchoolScoreClaim},
			{typeof(RspSchoolFundClaim), RspGameMsg.RspSchoolFundClaim},
			{typeof(RspLuckyTrip), RspGameMsg.RspLuckyTrip},
			{typeof(RspLuckyTripClaim), RspGameMsg.RspLuckyTripClaim},
			{typeof(RspLuckyTripPullRecord), RspGameMsg.RspLuckyTripPullRecord},
			{typeof(RspMagicAgeClaim), RspGameMsg.RspMagicAgeClaim},
			{typeof(RspGiftPackZeroClaim), RspGameMsg.RspGiftPackZeroClaim},
			{typeof(RspLuckyEggBuy), RspGameMsg.RspLuckyEggBuy},
			{typeof(RspLuckyEggClaim), RspGameMsg.RspLuckyEggClaim},
			{typeof(RspLuckyEggTaskClaim), RspGameMsg.RspLuckyEggTaskClaim},
			{typeof(RspLuckyEggFundClaim), RspGameMsg.RspLuckyEggFundClaim},
			{typeof(RspLuckyEggExchange), RspGameMsg.RspLuckyEggExchange},
			{typeof(RspLuckyEggDraw), RspGameMsg.RspLuckyEggDraw},
			{typeof(RspBingoCoinBuy), RspGameMsg.RspBingoCoinBuy},
			{typeof(RspBingoOpen), RspGameMsg.RspBingoOpen},
			{typeof(RspBingoClaim), RspGameMsg.RspBingoClaim},
			{typeof(RspBingoReset), RspGameMsg.RspBingoReset},
			{typeof(RspBingoTaskClaim), RspGameMsg.RspBingoTaskClaim},
			{typeof(RspBingoExchange), RspGameMsg.RspBingoExchange},
			{typeof(RspAccountAuth), RspGameMsg.RspAccountAuth},
			{typeof(RspCreateRole), RspGameMsg.RspCreateRole},
			{typeof(RspLoginRole), RspGameMsg.RspLoginRole},
			{typeof(RspServersAndRoles), RspGameMsg.RspServersAndRoles},
			{typeof(RspAntiKick), RspGameMsg.RspAntiKick},
			{typeof(RspUnRegisterAccountStatus), RspGameMsg.RspUnRegisterAccountStatus},
			{typeof(RspUnRegisterAccount), RspGameMsg.RspUnRegisterAccount},
			{typeof(RspCancelUnRegisterAccount), RspGameMsg.RspCancelUnRegisterAccount},
			{typeof(RspRoleFastLogin), RspGameMsg.RspRoleFastLogin},
			{typeof(RspQuicklyLoginRole), RspGameMsg.RspQuicklyLoginRole},
			{typeof(RspVsn), RspGameMsg.RspVsn},
			{typeof(RspNotice), RspGameMsg.RspNotice},
			{typeof(RspPushNotice), RspGameMsg.RspPushNotice},
			{typeof(RspNewMail), RspGameMsg.RspNewMail},
			{typeof(RspNewSysMail), RspGameMsg.RspNewSysMail},
			{typeof(RspAnnouncement), RspGameMsg.RspAnnouncement},
		};
		public static readonly Dictionary<Type, ReqGameMsg> ReqType = new Dictionary<Type, ReqGameMsg>
		{
			{typeof(ReqSync), ReqGameMsg.ReqSync},
			{typeof(ReqFbReport), ReqGameMsg.ReqFbReport},
			{typeof(ReqNotifyMsg), ReqGameMsg.ReqNotifyMsg},
			{typeof(ReqNotify), ReqGameMsg.ReqNotify},
			{typeof(ReqAdUpload), ReqGameMsg.ReqAdUpload},
			{typeof(ReqGm), ReqGameMsg.ReqGm},
			{typeof(ReqGmSync), ReqGameMsg.ReqGmSync},
			{typeof(ReqBattleGm), ReqGameMsg.ReqBattleGm},
			{typeof(ReqPrePay), ReqGameMsg.ReqPrePay},
			{typeof(ReqRewardPay), ReqGameMsg.ReqRewardPay},
			{typeof(ReqLoginRewardPay), ReqGameMsg.ReqLoginRewardPay},
			{typeof(ReqLivesGet), ReqGameMsg.ReqLivesGet},
			{typeof(ReqLivesSync), ReqGameMsg.ReqLivesSync},
			{typeof(ReqMailRead), ReqGameMsg.ReqMailRead},
			{typeof(ReqMailReward), ReqGameMsg.ReqMailReward},
			{typeof(ReqMailDelete), ReqGameMsg.ReqMailDelete},
			{typeof(ReqMailSync), ReqGameMsg.ReqMailSync},
			{typeof(ReqEquipWearOp), ReqGameMsg.ReqEquipWearOp},
			{typeof(ReqEquipLevelUp), ReqGameMsg.ReqEquipLevelUp},
			{typeof(ReqEquipSwitch), ReqGameMsg.ReqEquipSwitch},
			{typeof(ReqMainFightBegin), ReqGameMsg.ReqMainFightBegin},
			{typeof(ReqMainFightEnd), ReqGameMsg.ReqMainFightEnd},
			{typeof(ReqMainFightAdDouble), ReqGameMsg.ReqMainFightAdDouble},
			{typeof(ReqMainFightBox), ReqGameMsg.ReqMainFightBox},
			{typeof(ReqMainFightArchiveBegin), ReqGameMsg.ReqMainFightArchiveBegin},
			{typeof(ReqMainHangupClaim), ReqGameMsg.ReqMainHangupClaim},
			{typeof(ReqBattleEquipRefresh), ReqGameMsg.ReqBattleEquipRefresh},
			{typeof(ReqBattleTalentRefresh), ReqGameMsg.ReqBattleTalentRefresh},
			{typeof(ReqBattleTalentSelect), ReqGameMsg.ReqBattleTalentSelect},
			{typeof(ReqBattleLvUp), ReqGameMsg.ReqBattleLvUp},
			{typeof(ReqBattleWaveDone), ReqGameMsg.ReqBattleWaveDone},
			{typeof(ReqBattleEquipSkillSelect), ReqGameMsg.ReqBattleEquipSkillSelect},
			{typeof(ReqBattleEndlessEquip), ReqGameMsg.ReqBattleEndlessEquip},
			{typeof(ReqBattleEndlessWaveDone), ReqGameMsg.ReqBattleEndlessWaveDone},
			{typeof(ReqFightRevive), ReqGameMsg.ReqFightRevive},
			{typeof(ReqChangeName), ReqGameMsg.ReqChangeName},
			{typeof(ReqRankOp), ReqGameMsg.ReqRankOp},
			{typeof(ReqRankDigest), ReqGameMsg.ReqRankDigest},
			{typeof(ReqHeadOp), ReqGameMsg.ReqHeadOp},
			{typeof(ReqRedeemExchange), ReqGameMsg.ReqRedeemExchange},
			{typeof(ReqDiscordSync), ReqGameMsg.ReqDiscordSync},
			{typeof(ReqItemUseFreeAd), ReqGameMsg.ReqItemUseFreeAd},
			{typeof(ReqInviteReport), ReqGameMsg.ReqInviteReport},
			{typeof(ReqInviteSync), ReqGameMsg.ReqInviteSync},
			{typeof(ReqInviteClaim), ReqGameMsg.ReqInviteClaim},
			{typeof(ReqMonthCardClaim), ReqGameMsg.ReqMonthCardClaim},
			{typeof(ReqMonthCardDoubleClaim), ReqGameMsg.ReqMonthCardDoubleClaim},
			{typeof(ReqShopDailyBuy), ReqGameMsg.ReqShopDailyBuy},
			{typeof(ReqShopRecruitBuy), ReqGameMsg.ReqShopRecruitBuy},
			{typeof(ReqShopPackageBuy), ReqGameMsg.ReqShopPackageBuy},
			{typeof(ReqShopRecruitEquip), ReqGameMsg.ReqShopRecruitEquip},
			{typeof(ReqFirstChargeClaim), ReqGameMsg.ReqFirstChargeClaim},
			{typeof(ReqHeroUnlock), ReqGameMsg.ReqHeroUnlock},
			{typeof(ReqHeroLvUp), ReqGameMsg.ReqHeroLvUp},
			{typeof(ReqHeroStarUp), ReqGameMsg.ReqHeroStarUp},
			{typeof(ReqHeroInBattle), ReqGameMsg.ReqHeroInBattle},
			{typeof(ReqHeroReset), ReqGameMsg.ReqHeroReset},
			{typeof(ReqHeroLvUpAuto), ReqGameMsg.ReqHeroLvUpAuto},
			{typeof(ReqEndlessBegin), ReqGameMsg.ReqEndlessBegin},
			{typeof(ReqEndlessEnd), ReqGameMsg.ReqEndlessEnd},
			{typeof(ReqEndlessArchiveBegin), ReqGameMsg.ReqEndlessArchiveBegin},
			{typeof(ReqEndlessSweep), ReqGameMsg.ReqEndlessSweep},
			{typeof(ReqPassportClaim), ReqGameMsg.ReqPassportClaim},
			{typeof(ReqPassportUnlock), ReqGameMsg.ReqPassportUnlock},
			{typeof(ReqDailyPackClaim), ReqGameMsg.ReqDailyPackClaim},
			{typeof(ReqDailyPackSelect), ReqGameMsg.ReqDailyPackSelect},
			{typeof(ReqDailyPackOptional), ReqGameMsg.ReqDailyPackOptional},
			{typeof(ReqLuckyDraw), ReqGameMsg.ReqLuckyDraw},
			{typeof(ReqLuckyClaim), ReqGameMsg.ReqLuckyClaim},
			{typeof(ReqTriggerGiftConditionBuy), ReqGameMsg.ReqTriggerGiftConditionBuy},
			{typeof(ReqTriggerGiftClaim), ReqGameMsg.ReqTriggerGiftClaim},
			{typeof(ReqDailyFightBegin), ReqGameMsg.ReqDailyFightBegin},
			{typeof(ReqDailyFightEnd), ReqGameMsg.ReqDailyFightEnd},
			{typeof(ReqDailyFightArchiveBegin), ReqGameMsg.ReqDailyFightArchiveBegin},
			{typeof(ReqDailyFightBox), ReqGameMsg.ReqDailyFightBox},
			{typeof(ReqDailyFightWeekBox), ReqGameMsg.ReqDailyFightWeekBox},
			{typeof(ReqDailyFightSweep), ReqGameMsg.ReqDailyFightSweep},
			{typeof(ReqMagicDraw), ReqGameMsg.ReqMagicDraw},
			{typeof(ReqMagicClaim), ReqGameMsg.ReqMagicClaim},
			{typeof(ReqMagicFundClaim), ReqGameMsg.ReqMagicFundClaim},
			{typeof(ReqSecretFightBegin), ReqGameMsg.ReqSecretFightBegin},
			{typeof(ReqSecretFightEnd), ReqGameMsg.ReqSecretFightEnd},
			{typeof(ReqSecretFightBox), ReqGameMsg.ReqSecretFightBox},
			{typeof(ReqSecretFightArchiveBegin), ReqGameMsg.ReqSecretFightArchiveBegin},
			{typeof(ReqSecretBattleTalentRefresh), ReqGameMsg.ReqSecretBattleTalentRefresh},
			{typeof(ReqSecretBattleTalentSelect), ReqGameMsg.ReqSecretBattleTalentSelect},
			{typeof(ReqSecretBattleWaveDone), ReqGameMsg.ReqSecretBattleWaveDone},
			{typeof(ReqSecretBattleEquipSkillSelect), ReqGameMsg.ReqSecretBattleEquipSkillSelect},
			{typeof(ReqHeroEquipWear), ReqGameMsg.ReqHeroEquipWear},
			{typeof(ReqHeroEquipLevelUp), ReqGameMsg.ReqHeroEquipLevelUp},
			{typeof(ReqHeroEquipDown), ReqGameMsg.ReqHeroEquipDown},
			{typeof(ReqHeroEquipMerge), ReqGameMsg.ReqHeroEquipMerge},
			{typeof(ReqHeroEquipMergeFast), ReqGameMsg.ReqHeroEquipMergeFast},
			{typeof(ReqSchoolTaskClaim), ReqGameMsg.ReqSchoolTaskClaim},
			{typeof(ReqSchoolScoreClaim), ReqGameMsg.ReqSchoolScoreClaim},
			{typeof(ReqSchoolFundClaim), ReqGameMsg.ReqSchoolFundClaim},
			{typeof(ReqLuckyTrip), ReqGameMsg.ReqLuckyTrip},
			{typeof(ReqLuckyTripClaim), ReqGameMsg.ReqLuckyTripClaim},
			{typeof(ReqLuckyTripPullRecord), ReqGameMsg.ReqLuckyTripPullRecord},
			{typeof(ReqMagicAgeClaim), ReqGameMsg.ReqMagicAgeClaim},
			{typeof(ReqGiftPackZeroClaim), ReqGameMsg.ReqGiftPackZeroClaim},
			{typeof(ReqLuckyEggBuy), ReqGameMsg.ReqLuckyEggBuy},
			{typeof(ReqLuckyEggClaim), ReqGameMsg.ReqLuckyEggClaim},
			{typeof(ReqLuckyEggTaskClaim), ReqGameMsg.ReqLuckyEggTaskClaim},
			{typeof(ReqLuckyEggFundClaim), ReqGameMsg.ReqLuckyEggFundClaim},
			{typeof(ReqLuckyEggExchange), ReqGameMsg.ReqLuckyEggExchange},
			{typeof(ReqLuckyEggDraw), ReqGameMsg.ReqLuckyEggDraw},
			{typeof(ReqBingoCoinBuy), ReqGameMsg.ReqBingoCoinBuy},
			{typeof(ReqBingoOpen), ReqGameMsg.ReqBingoOpen},
			{typeof(ReqBingoClaim), ReqGameMsg.ReqBingoClaim},
			{typeof(ReqBingoReset), ReqGameMsg.ReqBingoReset},
			{typeof(ReqBingoTaskClaim), ReqGameMsg.ReqBingoTaskClaim},
			{typeof(ReqBingoExchange), ReqGameMsg.ReqBingoExchange},
			{typeof(ReqAccountAuth), ReqGameMsg.ReqAccountAuth},
			{typeof(ReqCreateRole), ReqGameMsg.ReqCreateRole},
			{typeof(ReqLoginRole), ReqGameMsg.ReqLoginRole},
			{typeof(ReqServersAndRoles), ReqGameMsg.ReqServersAndRoles},
			{typeof(ReqUnRegisterAccountStatus), ReqGameMsg.ReqUnRegisterAccountStatus},
			{typeof(ReqUnRegisterAccount), ReqGameMsg.ReqUnRegisterAccount},
			{typeof(ReqCancelUnRegisterAccount), ReqGameMsg.ReqCancelUnRegisterAccount},
			{typeof(ReqRoleFastLogin), ReqGameMsg.ReqRoleFastLogin},
			{typeof(ReqQuicklyLoginRole), ReqGameMsg.ReqQuicklyLoginRole},
			{typeof(ReqVsn), ReqGameMsg.ReqVsn},
			{typeof(ReqNotice), ReqGameMsg.ReqNotice},
		};
	}
}
