---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lizhenxiong.
--- DateTime: 2021/7/22 16:14
---

require("Common/System")
local CircularDynamicGroupItem = require("Binding/CircularDynamicGroupItem")
local List = require("Common/List")
local Binding = require("Binding/Binding")

--模块
---@class DynamicCollectionView
local DynamicCollectionView = bpcClass("DynamicCollectionView")

---构造函数
---@param source ObservableList
---@param binding DynamicCollectionBinding
function DynamicCollectionView:ctor(source, binding, viewModeVM)
    self.viewModeVM = viewModeVM
    self.refreshViewCallback = function(bJumpStart)
        self:RefreshView(bJumpStart)
    end

    ---@type DynamicCollectionViewModel
    self.collectionModeSetter = nil
    self.filter = nil
    self.sort = nil
    self.bindingSource = source
    self.binding = binding
    self.sortingList = List:New()
    self.indexedList = List:New() --- 对于source是List的这里记录的是List的索引；如果是dictionary，记录的是key
    self.count = 0
    self.viewChange = nil
    self.compareTo = function(lhs,rhs)
        local result = self.sort(lhs,rhs)
        return result
    end

    self.group = nil -- group的过滤函数
    
    ---@type CircularDynamicGroupItem[]|List
    self.groupItemList = List:New(CircularDynamicGroupItem)
    
    self.groupCompareTo = function(lhs,rhs)
        if lhs.groupIndex == rhs.groupIndex then
            return false
        end
        
        return lhs.groupIndex < rhs.groupIndex
    end
end

---@param dataContext DataContext
---@return DynamicCollectionView
function DynamicCollectionView:Build(dataContext)
    assert(dataContext ~= nil,"[DynamicCollectionView]Build dataContenxt is nil")

    if self.viewModeVM ~= nil then
        Binding():Target(self):For("collectionModeSetter"):To(self.viewModeVM):Build(dataContext)
        Binding():Target(self):For("dirty"):To(self.viewModeVM..".dirty", function(dirty)
            if dirty then
                self:refreshViewCallback(false)
            end
        end):Build(dataContext)
    end
end

---@public
function DynamicCollectionView:ApplyFilter()
    local index = 0
    self.count = 0
    
    --- 说明只有filter
    if self.sort == nil then
        self.indexedList:Clear()
    end

    self.bindingSource:ForEach(function(item, value)
        item = value or item
        
        local include = true
        -- invoke filter
        if self.filter ~= nil then
            include = self.filter(item)
        end

        index = index + 1
        
        if self.sort == nil then
            if include then
                self.count = self.count + 1
                local key = value ~= nil and item or index
                self.indexedList:Add(key)
            end
        else
            --索引的索引
            item.t__included = include
        end
    end)
end

---@public
function DynamicCollectionView:ApplySort()
    if self.sort == nil then
        return
    end

    -- reset sort List
    self.sortingList:Clear()
    self.indexedList:Clear()

    local index = 0
    self.bindingSource:ForEach(function(key, value)
        local item = value or key
        
        index = index + 1
        if not item.t__included then
            return
        end

        key = value ~= nil and key or index
        item.b_index = key
        self.sortingList:Add(item)
    end)
    
    -- sort List
    self.sortingList:Sort(self.compareTo)

    self.sortingList:ForEach(function(item)
        self.indexedList:Add(item.b_index)
    end)
    
    self.sortingList:Clear()
end

---@public
function DynamicCollectionView:ApplyGroup()
    if self.group == nil then
        return
    end

    self.groupItemList:Clear()

    local tmpIndex = 0
    -- 保证indexedList的顺序
    self.indexedList:ForEach(function(index)
        tmpIndex = tmpIndex + 1
        local item = self.bindingSource[index]
        local groupSource, sortIdx = self.group(item)

        if groupSource ~= nil then
            ---@type CircularDynamicGroupItem
            local groupItem = self.groupItemList:Find(function(tmpItem)
                return tmpItem.groupIndex == sortIdx
            end)

            if groupItem == nil then
                groupItem = CircularDynamicGroupItem(groupSource, sortIdx)
                self.groupItemList:Add(groupItem)
            end

            groupItem.indexedList:Add(tmpIndex)
        end
    end)
    
    self.groupItemList:Sort(self.groupCompareTo)
end

---@public
---@param bJumpStart boolean @是否需要跳到列表的开头
function DynamicCollectionView:RefreshView(bJumpStart)
    --- no valid binding source
    if not self.bindingSource then
        return
    end

    --- already unbound,ignore update view
    if not self.binding:IsBound() then
        return
    end

    if self.collectionModeSetter ~= nil then
        self.sort = self.collectionModeSetter.sort
        self.filter = self.collectionModeSetter.filter
        self.group = self.collectionModeSetter.group
    end

    self:ApplyFilter()
    self:ApplySort()
    self:ApplyGroup()

    if self.viewChange ~= nil and type(self.viewChange) == "function" then
        self.viewChange(bJumpStart)
    end
end

return DynamicCollectionView