---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenyu.
--- DateTime: 2022/9/22 16:51
---

local BaseDlg = require("Client/UI/BaseDlg")
local LoginData = require("Data/LoginData")

---@class SelectServerDlg:BaseDlg
local SelectServerDlg = bpcClass("SelectServerDlg", BaseDlg)

SelectServerDlg.uiMap = {
    ["existingRoleTab"] = { LuaUT.GameObject, "Content/tab/existingRole" },
    ["warzoneTab"] = { LuaUT.GameObject, "Content/tab/warzone" },
    ["serversScrollView"] = { LuaUT.LoopScrollView, "Content/serversScrollView" },
    ["closeBtn"] = { LuaUT.Button, "Content/TopInfoBar/CloseBtn" },

    ["dlgName"] = {LuaUT.Text, "Content/TopInfoBar/Name"},
    ["maintainText"] = {LuaUT.Text, "Content/TopInfoBar/state_2/Text (TMP)"},
    ["waitOpenText"] = {LuaUT.Text, "Content/TopInfoBar/state/Text (TMP)"},
    ["normalText"] = {LuaUT.Text, "Content/TopInfoBar/state_1/Text (TMP)"},
    ["existingRoleText"] = {LuaUT.Text, "Content/tab/existingRole/Text (TMP)"},
    ["warzoneText"] = {LuaUT.Text, "Content/tab/warzone/Text (TMP)"},
}

---@class SelectServerDlgTab
---@field selectImg UnityEngine.UI.Image
---@field text TMPro.TextMeshProUGUI
---@field btn UnityEngine.UI.Button
SelectServerDlg.tabMap = {
    ["selectImg"] = { LuaUT.GameObject, "select" },
    ["btn"] = { LuaUT.Button, "" },
    ["text"] = { LuaUT.Text, "Text (TMP)" },
}

SelectServerDlg.serverItemMap = {
    ["btn"] = { LuaUT.Button, "" },
    ["stateIcon"] = { LuaUT.Image, "StateIcon" },
    ["serverName"] = { LuaUT.Text, "ServerName" },
    ["roleGroup"] = { LuaUT.CanvasGroup, "role" },
    ["roleLv"] = { LuaUT.Text, "role/RoleLv" },
    ["roleName"] = { LuaUT.Text, "role/RoleName" },
    ["icon"] = { LuaUT.Image, "role/icon" },
    ["frame"] = { LuaUT.Image, "role/frame" },
}

function SelectServerDlg:ctor()
    SelectServerDlg.super.ctor(self)
    self.curTabIndex = 0 --0:exitRole 1:warzone1 2:warzone2 ..
    ---@type SelectServerDlgTab[]
    self.tabs = {}
end

function SelectServerDlg:OnUIReady()
    self.uiMap = self:Bind(self.rootObj, SelectServerDlg.uiMap)

    local uiMap = self.uiMap
    self.tabs[0] = self:Bind(uiMap.existingRoleTab, SelectServerDlg.tabMap)
    self.tabs[1] = self:Bind(uiMap.warzoneTab, SelectServerDlg.tabMap)

    for _, v in pairs(self.tabs) do
        local tab = v;
        tab.setTab = function(isSelected)
            if (isSelected) then
                tab.selectImg:SetActive(true)
                UIHelper.SetTextHexColor(tab.text, "#30281C")
            else
                tab.selectImg:SetActive(false)
                UIHelper.SetTextHexColor(tab.text, "#958E7A")
            end
        end
    end

    self.onServersChanged = function()
        self:RefreshServers()
    end

    self:SetTextOnce()
    self:BindClick()
    self:NetBinding()

    self:RefreshTab()
    self:RefreshServers()
end

function SelectServerDlg:OnDestroy()
    self:NetUnbinding()
end

function SelectServerDlg:SetTextOnce()
    local uiMap=self.uiMap
    
    UIHelper.SetText(uiMap["warzoneText"],string.format(LTH:GetGlobal("login_txt_2"),1))
    
    UIHelper.SetText(uiMap["maintainText"],LTH:GetGlobal("server_state_3"))
    UIHelper.SetText(uiMap["normalText"],LTH:GetGlobal("server_state_1"))
    UIHelper.SetText(uiMap["existingRoleText"],LTH:GetGlobal("login_txt_1"))
    UIHelper.SetText(uiMap["waitOpenText"],LTH:GetGlobal("server_state_2"))
    UIHelper.SetText(uiMap["dlgName"],LTH:GetGlobal("login_title_1"))
end

function SelectServerDlg:RefreshServers()
    --刷新服务器列表数据
    --如果有战区再修改
    if (self.curTabIndex == 0) then
        --筛选有角色的服务器
        self.serverData = {}
        LoginData.servers:ForEach(function(item)
            if (item.roleData) then
                table.insert(self.serverData, item)
            end
        end)
    else
        self.serverData = {}
        LoginData.servers:ForEach(function(item)
            table.insert(self.serverData, item)
        end)
    end

    --刷新显示服务器
    if (self.serverScrollView == nil) then
        local getPrefabFunc = function(index)
            return "UI/Prefabs/Startup/ServerItem", SelectServerDlg.serverItemMap
        end

        local onCreateFunc = function(item, index)
            local uiMap = item.uiMap

            ---@param serverData ServerItemData
            item.setServerData = function(serverData)
                local roleData = serverData.roleData
                if roleData then
                    UIHelper.SetCanvasGroup(uiMap.roleGroup, true)
                    --背景框 
                    self:SetIconSprite(uiMap.frame, ItemHelper.GetAvatarFrameIconPath(roleData.head_frame))
                    --头像
                    self:SetIconSprite(uiMap.icon, ItemHelper.GetAvatarIconPath(roleData.logo))
                    --等级 todo先直接用经验
                    UIHelper.SetText(uiMap.roleLv, "Lv." .. roleData.exp)
                    --名字
                    UIHelper.SetText(uiMap.roleName, roleData.name)
                else
                    UIHelper.SetCanvasGroup(uiMap.roleGroup, false)
                end

                --服务器名字
                UIHelper.SetText(uiMap.serverName, serverData.serverData.name)
            end

            self:SetBtnClick(uiMap.btn, function()
                local serverItem = self.serverData[item.cellIdx]

                if serverItem then
                    LoginData:SetSvrId(serverItem.serverData.sid)
                    UIManager:Close(self)
                end
            end)
        end

        local refreshFunc = function(item, index)
            local serverItem = self.serverData[item.cellIdx]

            if serverItem then
                item.setServerData(self.serverData[index])
            end
        end

        self.serverScrollView = self:SetLoopScroll(self.uiMap.serversScrollView, #self.serverData, getPrefabFunc
        , onCreateFunc, refreshFunc)
    else
        self.lastSelectedCel = nil
        self.serverScrollView:ShowList(#self.serverData, true)
    end
end

function SelectServerDlg:RefreshTab()
    if (self.lastTabIndex ~= nil) then
        self.tabs[self.lastTabIndex].setTab(false)
    end
    self.tabs[self.curTabIndex].setTab(true)
end

function SelectServerDlg:BindClick()
    local uiMap = self.uiMap

    self:SetBtnClick(uiMap["closeBtn"], function()
        UIManager:Close(self)
    end)

    for i = 0, 1 do
        local index = i
        self:SetBtnClick(self.tabs[i].btn, function()
            if (self.curTabIndex == index) then
                return
            end

            self.lastTabIndex = self.curTabIndex
            self.curTabIndex = index

            self:RefreshTab()
            self:RefreshServers()
        end)
    end
end

function SelectServerDlg:NetBinding()
    LoginData.servers:BindCollectionChanged(self.onServersChanged)
end

function SelectServerDlg:NetUnbinding()
    LoginData.servers:UnBindCollectionChanged(self.onServersChanged)
end

return SelectServerDlg