---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuancan.
--- DateTime: 2022/2/22 7:56 PM
---

---@class LocalizationConfig
---@field key string @用于社区、客服、公告模块的多语言初始化
---@field id number @用于BI上报

---@class Localization
---@field languageCode string[]
---@field configData table<string,LocaleConfigItem>
---@field currentConfig LocaleConfigItem
---@field currentFont TMPro.TMP_FontAsset
local Localization = {}
local LanguageSaveKey = "Locale"
local DefaultLanguage = "en"
--多语言支持新
-- --支持的语言类型
-- 值仅用于内部区分以及记录用户实际选择语言
--- 参考BI文档
---
require("Binding/ChainedSource")
Localization.languageType = {
    en = 0, --- 英语  English
    cn = 1, --- 简体中文  Chinese
    fr = 2, --- 法语  French
    it = 3, --- 意大利  Italian
    de = 4, --- 德语  German
    es = 5, --- 西班牙语  Spanish
    nl = 6, --- 荷兰语  Dutch
    ru = 7, --- 俄语  Russian
    ko = 8, --- 韩语  Korean
    ja = 9, --- 日语  Japanese
    hu = 10, --- 匈牙利语  Hungarian
    pt = 11, --- 葡萄牙语  Portuguese
    ar = 12, --- 阿拉伯语  Arabic
    zh = 13, --- 繁体中文  ChineseTW
    tr = 14, --- 土耳其语  Turkish
    th = 15, --- 泰语  Thai
    ms = 16, --- 马来语  Malay
    vi = 17, --- 越南语  Vietnamese
    id = 18, --- 印尼语  Indonesian
    be = 19, --- 白俄罗斯  Belarusian
    bg = 20, --- 保加利亚  Bulgarian
    ca = 21, --- 加泰罗尼亚语的  Catalan
    cs = 23, --- 捷克  Czech
    da = 24, --- 丹麦  Danish
    et = 25, --- 爱沙尼亚  Estonian
    fo = 26, --- 法罗人  Faroese
    fi = 27, --- 芬兰  Finnish
    el = 28, --- 希腊  Greek
    he = 29, --- 希伯来语  Hebrew
    is = 30, --- 冰岛  Icelandic
    eu = 31, --- 巴斯克  Basque
    lv = 32, --- 拉脱维亚  Latvian
    lt = 33, --- 立陶宛  Lithuanian
    nb = 34, --- 挪威(Bokm?l)  Norwegian(Bokm?l)
    pl = 35, --- 波兰的  Polish
    ro = 36, --- 罗马尼亚  Romanian
    sh = 37, --- 塞尔维亚-克罗地亚语  SerboCroatian
    sk = 38, --- 斯洛伐克语  Slovak
    sl = 39, --- 斯洛维尼亚语  Slovenian
    sv = 40, --- 瑞典  Swedish
    uk = 41, --- 乌克兰  Ukrainian
    af = 42, --- 南非荷兰语  Afrikaans
    gl = 42, --- 加利西亚语的  Galician
    sa = 43, --- 梵文  Sanskrit
    se = 44, --- 萨米人(北部)  Sami(Northern)
    sq = 45, --- 阿尔巴尼亚  Albanian
    sw = 46, --- 斯瓦希里语  Swahili
    syr = 47, --- 叙利亚的  Syriac
    ta = 48, --- 泰米尔  Tamil
    te = 49, --- 泰卢固语  Telugu
    tl = 50, --- 塔加拉族语  Tagalog
    tn = 51, --- 茨瓦纳语  Tswana
    ts = 52, --- 特松加  Tsonga
    tt = 53, --- 鞑靼人  Tatar
    ur = 54, --- 乌尔都语  Urdu
    uz = 55, --- 乌兹别克斯坦(拉丁)  Uzbek(Latin)
    qu = 56, --- 盖丘亚语  Quechua
    gu = 57, --- 古吉拉特语  Gujarati
    ps = 58, --- 普什图语  Pashto
    pa = 59, --- 旁遮普语  Punjabi
    hi = 60, --- 北印度语  Hindi
    xh = 61, --- 科萨人  Xhosa
    hy = 62, --- 亚美尼亚  Armenian
    fa = 63, --- 波斯语  Farsi
    ka = 64, --- 乔治亚语  Georgian
    kk = 65, --- 哈萨克斯坦  Kazakh
    kn = 66, --- 埃纳德语  Kannada
    kok = 67, --- 贡根语  Konkani
    az = 68, --- 阿塞拜疆(拉丁)  Azeri(Latin)
    ky = 69, --- 吉尔吉斯语  Kyrgyz
    dv = 70, --- 迪维西语  Divehi
    mi = 71, --- 毛利  Maori
    mk = 72, --- FYRO马其顿  FYRO Macedonian
    mn = 73, --- 蒙古  Mongolian
    mr = 74, --- 马拉地语  Marathi
    mt = 75, --- 马耳他  Maltese
    cy = 76, --- 威尔士  Welsh
    ns = 77, --- 北梭托语  Northern Sotho
    eo = 78, --- 世界语  Esperanto
    hr = 79, --- 克罗地亚  Croatian
}

--- 获取项目组多语言配置信息
local function Prepare()
    Localization.languageCode = {}
    for key, value in pairs(Localization.languageType) do
        Localization.languageCode[value] = key
    end

    local config = require("Config/LocaleConfigData")
    Localization.configData = config
end

local function GetSystemLanguage()
    local countryCode = CS.DH.NativeCore.Platform.DeviceUtility.GetLanguage()
    local languageCode = DefaultLanguage
    local splitCode = Split(countryCode,'_')

    --- 检查返回的语言格式是否正确，若不正确将使用默认的语言
    if #splitCode ~= 2 then
        return languageCode
    end

    --- 针对目前的多语言规则，特殊处理TW和其他简体中文的情况
    if countryCode == "zh_TW" then
        languageCode = "tw"
    elseif splitCode[1] == "zh" then
        languageCode = "cn"
    else
        languageCode = splitCode[1]
    end
    
    return languageCode
end

local function GetLocalLanguage()
    return nil
    --local playerPrefs = CS.UnityEngine.PlayerPrefs
    --if not playerPrefs.HasKey(LanguageSaveKey) then
    --    return nil
    --end
    --
    --local code = playerPrefs.GetString(LanguageSaveKey,DefaultLanguage)
    ----- 由于版本升级，可能上次存储的语言已经不支持，回滚到获取系统语言
    --if Localization.languageCode[code] == nil then
    --    return nil
    --end
end

--- 获取当前已选择的语言，若还未选择语言则获取系统语言
local function PrepareCurrentLanguage()
    local languageCode = GetLocalLanguage()
    if languageCode == nil then
        languageCode = GetSystemLanguage()
    end
    
    Localization.ChangeLanguage(languageCode,function()
        --- 语言切换完成
    end)
end

---@param code string @多语言文本ID：cn,en等
---@return LocaleConfigItem
local function GetLanguageConfig(code)
    local configData = Localization.configData
    local config = configData[code]
    --- 若不存在对于该语言的配置信息，则使用默认的配置信息
    if config == nil then
        return configData.default
    else
        return config
    end
end

local function NotifyOnLocalize()
    for _, v in pairs(Localization.onLocalize) do
        v.OnLocalize()
    end
end

--- 多语言切换接口，切换多语言为异步操作，需要等待多语言完成后进行其他操作
--- 多语言切换可能会触发资源更新逻辑
---@param code number | string @多语言数字ID：1,2,3或者多语言文本ID：cn,en等
---@param callback fun():void @多语言切换完成回调,仅适用于UI表现
function Localization.ChangeLanguage(code, callback)
    if Localization.configData == nil then
        error("需要先初始化多语言模块")
    end

    local languageKey = nil
    if type(code) == "number" then
        languageKey = Localization.languageCode[code]
    else
        languageKey = code
        if not Localization.languageType[code] then
            error("不支持的多语言Code" .. tostring(code))
        end
    end

    if not languageKey then
        error("不支持的多语言Code" .. tostring(code))
    end

    local config = GetLanguageConfig(languageKey)
    --- 配置信息一致，不需要对字体或者文本格式进行处理
    if config == Localization.currentConfig then
        NotifyOnLocalize()
        callback()
        return
    end

    local AM = CS.DH.Asset.AssetsManager
    --- 加载字体资源
    --AM.LoadAssetAsync(config.fontPath, function(result)
    --    Localization.currentFont = result
    --    local nativeLocale = CS.DH.Localize.Localization.Instance
    --    nativeLocale:ChangeLanguage(Json.encode(config),result)
    --    local binding = require("Binding/BindingManager")
    --    binding:OnLocalize()
    --    NotifyOnLocalize()
    --end)
end

--- 注册多语言切换回调
---@param target any @任意实现了OnLocalize函数的类型对象
function Localization.RegisterLocalize(target)
    if target.OnLocalize == nil then
        return
    end
    Localization.onLocalize[target] = target
end

--- 取消注册多语言切换回调
---@param target any @任意实现了OnLocalize函数的类型对象
function Localization.UnRegisterLocalize(target)
    Localization.onLocalize[target] = nil
end

---@private
Localization.onLocalize = {}
Prepare()
PrepareCurrentLanguage()

return Localization